# Generated by Django 4.1.3 on 2022-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='images/perfil.jpeg', null=True, upload_to=''),
        ),
    ]
