# Generated by Django 4.1.3 on 2022-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='images/perfil.jpeg', null=True, upload_to='users'),
        ),
    ]
