# Generated by Django 4.1.3 on 2022-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fondo',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='users_fondo'),
        ),
    ]
