# Generated by Django 4.1.3 on 2026-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
