# Generated by Django 4.1.3 on 2026-04-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
