# Generated by Django 4.1.3 on 2026-04-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descripcion',
            new_name='bio',
        ),
    ]
