# Generated by Django 4.1.3 on 2026-03-30 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('transmitter', 'receiver')},
        ),
    ]
